<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)
x = np_array
x[1:10:2]

array(['b2', 'd4', 'f6', 'h8', 'j10'], dtype='<U3')

In [3]:
x[::-1] # what's dtype?

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [4]:
x[1:2]

array(['b2'], dtype='<U3')

## 1.2 Arrays only | Subsetting by masking

In [5]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[np_array > 1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np_array[~(np_array < 3)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [12]:
np_array[(np_array > 3) | (np_array > 8)]

array([ 4,  5,  6,  7,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [14]:
py_list_2d[3]

[4, 'D']

In [15]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [17]:
py_list_2d[3][1]

'D'

In [18]:
np_array_2d[5, 1]

'F'

In [19]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [20]:
np_array_2d[:2]

array([['1', 'A'],
       ['2', 'B']], dtype='<U11')

In [21]:
py_list_2d[:3][0]

[1, 'A']

In [22]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [23]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [26]:
x=[1,2]*0
x

[]

In [27]:
x=[0,0]*5
x

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [29]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [30]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [32]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [33]:
a=(1, 2, 3)
print(a[0])

1


In [35]:
a[0]+=[1]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [36]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes