<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

## 1.2 Accessing data from a list (or array)

In [4]:
np_super_names[1]

'Iron Man'

In [7]:
np_real_names[-3]

'Natasha Romanoff'

## 1.3 Accessing data from a dictionary

In [8]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [9]:
superhero_info["Tony Stark"]

'Iron Man'

In [10]:
superhero_info["Iron Man"]

KeyError: 'Iron Man'

In [11]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

len(py_list_2d)

10

In [15]:
len(np_array_2d)

10

In [16]:
np_array_2d.shape

(10, 2)

In [17]:
py_list_2d.shape

AttributeError: 'list' object has no attribute 'shape'

## 2.2 Arrays are fussy about type

In [18]:
py_list = [1, 1.5, 'A']
py_list

[1, 1.5, 'A']

In [19]:
np_array = np.array(py_list)
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 
np_array + 1

array([2, 3, 4, 5, 6])

In [21]:
py_list + 1

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [22]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [23]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [24]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list*10 #why the line break?

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [26]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [28]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [30]:
py_list == 1

False

In [31]:
np_array == 3

array([False, False,  True, False, False])

## 2.8 Mathematics

In [32]:
min(py_list)

1

In [33]:
np_array.min

<function ndarray.min>

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes